version: "3.9"
services:
  noscai-node-app:
    image: noscai-image
    container_name: noscai-app
    ports:
      - "9000:3000"
    restart: always
    links:
      - noscai-postgres
    depends_on:
      noscai-postgres:
        condition: service_healthy

  noscai-postgres:
    image: postgres
    container_name: noscai-db
    ports:
      - 9001:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=noscai
      - POSTGRES_DB=noscai_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noscai -d noscai_db"]
      interval: 10s      # Check every 10 seconds
      timeout: 3s        # Wait up to 5 seconds for the check
      retries: 3         # After 5 failed attempts, mark as unhealthy