version: "3.9"
services:
  noscai-node-app:
    build: .
    container_name: noscai-image
    ports:
      - "9000:3000"
    restart: always
    links:
      - noscai-postgres
    depends_on:
      noscai-postgres:
        condition: service_healthy

  noscai-postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=noscai
      - POSTGRES_DB=noscai_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noscai"]
      interval: 10s      # Check every 10 seconds
      timeout: 3s        # Wait up to 5 seconds for the check
      retries: 3         # After 5 failed attempts, mark as unhealthy